import { StyleSheet } from "react-native";
export const colors = {
  green: "#245b44",
  dark: "#183f32",
  text: "#263e31",
  muted: "#627267",
  background: "#f5f7f1",
  border: "#dce4d7",
  cream: "#e9efdc",
  white: "#ffffff",
  error: "#a13427",
};
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    padding: 24,
    gap: 18,
    width: "100%",
    maxWidth: 620,
    alignSelf: "center",
    flexGrow: 1,
  },
  title: {
    fontSize: 29,
    fontWeight: "700",
    color: colors.text,
    lineHeight: 37,
  },
  heading: { fontSize: 19, fontWeight: "700", color: colors.text },
  eyebrow: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1.5,
    color: colors.green,
  },
  text: { fontSize: 15, lineHeight: 23, color: colors.text },
  muted: { fontSize: 13, lineHeight: 21, color: colors.muted },
  card: {
    padding: 20,
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    gap: 10,
  },
  notice: { padding: 15, borderRadius: 12, backgroundColor: colors.cream },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#9eae9a",
    borderRadius: 10,
    padding: 15,
    backgroundColor: colors.white,
    color: colors.text,
    minHeight: 52,
    fontSize: 16,
  },
  error: { color: colors.error, fontSize: 13, marginTop: 6 },
});
