// Report Export Utilities
// Handles CSV and PDF export formatting for conservation reports

/**
 * Convert report data to CSV format
 */
function exportToCSV(reportData) {
  const { reportType, summary, incidents, patrols, reports } = reportData;

  let csv = "";

  // Header
  csv += `Report Type,${reportType}\n`;
  csv += `Generated At,${reportData.generatedAt}\n`;
  csv += `Generated By,${reportData.generatedBy.name} (${reportData.generatedBy.role})\n`;
  csv += "\n";

  // Filters
  csv += "FILTERS\n";
  if (reportData.filters.dateFrom) {
    csv += `Date From,${reportData.filters.dateFrom}\n`;
  }
  if (reportData.filters.dateTo) {
    csv += `Date To,${reportData.filters.dateTo}\n`;
  }
  if (reportData.filters.area) {
    csv += `Area,${reportData.filters.area}\n`;
  }
  if (reportData.filters.type) {
    csv += `Type,${reportData.filters.type}\n`;
  }
  if (reportData.filters.status) {
    csv += `Status,${reportData.filters.status}\n`;
  }
  if (reportData.filters.priority) {
    csv += `Priority,${reportData.filters.priority}\n`;
  }
  csv += "\n";

  // Summary
  csv += "SUMMARY\n";
  if (reportType === "INCIDENT_REPORT") {
    csv += `Total Incidents,${summary.totalIncidents}\n`;
    csv += "\nBy Type\n";
    csv += "Type,Count\n";
    summary.byType.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
    csv += "\nBy Status\n";
    csv += "Status,Count\n";
    summary.byStatus.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
  } else if (reportType === "PATROL_OPERATIONS_REPORT") {
    csv += `Total Patrols,${summary.totalPatrols}\n`;
    csv += "\nBy Status\n";
    csv += "Status,Count\n";
    summary.byStatus.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
    csv += "\nBy Type\n";
    csv += "Type,Count\n";
    summary.byType.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
    csv += "\nBy Priority\n";
    csv += "Priority,Count\n";
    summary.byPriority.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
  } else if (reportType === "CONFLICT_TREND_REPORT") {
    csv += `Total Reports,${summary.totalReports}\n`;
    csv += `Conflict Reports,${summary.conflictReports}\n`;
    csv += "\nBy Type\n";
    csv += "Type,Count\n";
    summary.byType.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
    csv += "\nBy Status\n";
    csv += "Status,Count\n";
    summary.byStatus.forEach((item) => {
      csv += `${item.key},${item.count}\n`;
    });
    csv += "\nBy Area\n";
    csv += "Area,Count\n";
    summary.byArea.forEach((item) => {
      csv += `"${escapeCSV(item.key)}",${item.count}\n`;
    });
  }
  csv += "\n";

  // Detailed records
  if (incidents && incidents.length > 0) {
    csv += "INCIDENTS\n";
    csv += "ID,Title,Type,Status,Reported At,Occurred At,Location,Reporter,Role,Patrol Route\n";
    incidents.forEach((inc) => {
      csv += `${inc.id},"${escapeCSV(inc.title)}",${inc.type},${inc.status},${inc.reportedAt},${inc.occurredAt || "N/A"},"${escapeCSV(inc.location)}",${inc.reporterName},${inc.reporterRole},${inc.patrolRoute}\n`;
    });
  }

  if (patrols && patrols.length > 0) {
    csv += "PATROLS\n";
    csv += "ID,Route Name,Type,Priority,Status,Scheduled Date,Actual Start,Actual End,Location,Ranger,Created By,Waypoints,Incidents\n";
    patrols.forEach((patrol) => {
      csv += `${patrol.id},"${escapeCSV(patrol.routeName)}",${patrol.type},${patrol.priority},${patrol.status},${patrol.scheduledDate || "N/A"},${patrol.actualStartTime || "N/A"},${patrol.actualEndTime || "N/A"},"${escapeCSV(patrol.location)}",${patrol.rangerName},${patrol.createdBy},${patrol.waypointCount},${patrol.incidentCount}\n`;
    });
  }

  if (reports && reports.length > 0) {
    csv += "COMMUNITY REPORTS\n";
    csv += "ID,Type,Species,Status,Submitted At,Location,Anonymous\n";
    reports.forEach((report) => {
      csv += `${report.id},${report.type},"${escapeCSV(report.species)}",${report.status},${report.submittedAt},"${escapeCSV(report.location)}",${report.isAnonymous}\n`;
    });
  }

  return csv;
}

/**
 * Escape CSV special characters
 */
function escapeCSV(value) {
  if (value === null || value === undefined) return "";
  return String(value).replace(/"/g, '""');
}

/**
 * Convert report data to simple HTML for PDF generation
 * Uses basic HTML that can be converted to PDF by frontend or external service
 */
function exportToHTML(reportData) {
  const { reportType, summary, incidents, patrols, reports } = reportData;

  let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${reportType}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    h1 { color: #2c5530; border-bottom: 2px solid #2c5530; padding-bottom: 10px; }
    h2 { color: #3d7042; margin-top: 30px; }
    h3 { color: #4d8052; margin-top: 20px; }
    .header { margin-bottom: 30px; }
    .meta { color: #666; font-size: 0.9em; }
    .filters { background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0; }
    .summary { margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th { background: #2c5530; color: white; padding: 10px; text-align: left; }
    td { padding: 8px; border-bottom: 1px solid #ddd; }
    tr:hover { background: #f9f9f9; }
    .stat { display: inline-block; margin: 10px 20px 10px 0; }
    .stat-label { font-weight: bold; color: #2c5530; }
    .stat-value { font-size: 1.3em; color: #3d7042; }
  </style>
</head>
<body>
  <div class="header">
    <h1>WildGuard Conservation Report</h1>
    <h2>${formatReportType(reportType)}</h2>
    <div class="meta">
      <p><strong>Generated:</strong> ${new Date(reportData.generatedAt).toLocaleString()}</p>
      <p><strong>Generated By:</strong> ${reportData.generatedBy.name} (${reportData.generatedBy.role})</p>
    </div>
  </div>

  <div class="filters">
    <h3>Report Filters</h3>
    ${reportData.filters.dateFrom ? `<p><strong>Date From:</strong> ${new Date(reportData.filters.dateFrom).toLocaleDateString()}</p>` : ""}
    ${reportData.filters.dateTo ? `<p><strong>Date To:</strong> ${new Date(reportData.filters.dateTo).toLocaleDateString()}</p>` : ""}
    ${reportData.filters.area ? `<p><strong>Area:</strong> ${reportData.filters.area}</p>` : ""}
    ${reportData.filters.type ? `<p><strong>Type:</strong> ${reportData.filters.type}</p>` : ""}
    ${reportData.filters.status ? `<p><strong>Status:</strong> ${reportData.filters.status}</p>` : ""}
    ${reportData.filters.priority ? `<p><strong>Priority:</strong> ${reportData.filters.priority}</p>` : ""}
  </div>

  <div class="summary">
    <h2>Summary</h2>`;

  // Type-specific summary
  if (reportType === "INCIDENT_REPORT") {
    html += `
    <div class="stat">
      <div class="stat-label">Total Incidents</div>
      <div class="stat-value">${summary.totalIncidents}</div>
    </div>
    
    <h3>Incidents by Type</h3>
    <table>
      <tr><th>Type</th><th>Count</th></tr>
      ${summary.byType.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>
    
    <h3>Incidents by Status</h3>
    <table>
      <tr><th>Status</th><th>Count</th></tr>
      ${summary.byStatus.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>`;
  } else if (reportType === "PATROL_OPERATIONS_REPORT") {
    html += `
    <div class="stat">
      <div class="stat-label">Total Patrols</div>
      <div class="stat-value">${summary.totalPatrols}</div>
    </div>
    
    <h3>Patrols by Status</h3>
    <table>
      <tr><th>Status</th><th>Count</th></tr>
      ${summary.byStatus.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>
    
    <h3>Patrols by Type</h3>
    <table>
      <tr><th>Type</th><th>Count</th></tr>
      ${summary.byType.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>
    
    <h3>Patrols by Priority</h3>
    <table>
      <tr><th>Priority</th><th>Count</th></tr>
      ${summary.byPriority.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>`;
  } else if (reportType === "CONFLICT_TREND_REPORT") {
    html += `
    <div class="stat">
      <div class="stat-label">Total Reports</div>
      <div class="stat-value">${summary.totalReports}</div>
    </div>
    <div class="stat">
      <div class="stat-label">Conflict Reports</div>
      <div class="stat-value">${summary.conflictReports}</div>
    </div>
    
    <h3>Reports by Type</h3>
    <table>
      <tr><th>Type</th><th>Count</th></tr>
      ${summary.byType.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>
    
    <h3>Reports by Status</h3>
    <table>
      <tr><th>Status</th><th>Count</th></tr>
      ${summary.byStatus.map((item) => `<tr><td>${item.key}</td><td>${item.count}</td></tr>`).join("")}
    </table>
    
    <h3>Reports by Area</h3>
    <table>
      <tr><th>Area</th><th>Count</th></tr>
      ${summary.byArea.slice(0, 10).map((item) => `<tr><td>${escapeHTML(item.key)}</td><td>${item.count}</td></tr>`).join("")}
    </table>`;
  }

  html += `</div>`;

  // Detailed records
  if (incidents && incidents.length > 0) {
    html += `
    <h2>Incident Details</h2>
    <table>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Type</th>
        <th>Status</th>
        <th>Reported</th>
        <th>Location</th>
        <th>Reporter</th>
      </tr>
      ${incidents.slice(0, 50).map((inc) => `
        <tr>
          <td>${inc.id.substring(0, 8)}</td>
          <td>${escapeHTML(inc.title)}</td>
          <td>${inc.type}</td>
          <td>${inc.status}</td>
          <td>${new Date(inc.reportedAt).toLocaleDateString()}</td>
          <td>${escapeHTML(inc.location)}</td>
          <td>${inc.reporterName}</td>
        </tr>
      `).join("")}
    </table>
    ${incidents.length > 50 ? `<p><em>Showing first 50 of ${incidents.length} incidents. Export to CSV for full data.</em></p>` : ""}`;
  }

  if (patrols && patrols.length > 0) {
    html += `
    <h2>Patrol Details</h2>
    <table>
      <tr>
        <th>ID</th>
        <th>Route</th>
        <th>Type</th>
        <th>Status</th>
        <th>Ranger</th>
        <th>Scheduled</th>
        <th>Waypoints</th>
        <th>Incidents</th>
      </tr>
      ${patrols.slice(0, 50).map((patrol) => `
        <tr>
          <td>${patrol.id.substring(0, 8)}</td>
          <td>${escapeHTML(patrol.routeName)}</td>
          <td>${patrol.type}</td>
          <td>${patrol.status}</td>
          <td>${patrol.rangerName}</td>
          <td>${patrol.scheduledDate ? new Date(patrol.scheduledDate).toLocaleDateString() : "N/A"}</td>
          <td>${patrol.waypointCount}</td>
          <td>${patrol.incidentCount}</td>
        </tr>
      `).join("")}
    </table>
    ${patrols.length > 50 ? `<p><em>Showing first 50 of ${patrols.length} patrols. Export to CSV for full data.</em></p>` : ""}`;
  }

  if (reports && reports.length > 0) {
    html += `
    <h2>Community Report Details</h2>
    <table>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Species</th>
        <th>Status</th>
        <th>Submitted</th>
        <th>Location</th>
      </tr>
      ${reports.slice(0, 50).map((report) => `
        <tr>
          <td>${report.id.substring(0, 8)}</td>
          <td>${report.type}</td>
          <td>${escapeHTML(report.species)}</td>
          <td>${report.status}</td>
          <td>${new Date(report.submittedAt).toLocaleDateString()}</td>
          <td>${escapeHTML(report.location)}</td>
        </tr>
      `).join("")}
    </table>
    ${reports.length > 50 ? `<p><em>Showing first 50 of ${reports.length} reports. Export to CSV for full data.</em></p>` : ""}`;
  }

  html += `
  <div style="margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc; color: #666; font-size: 0.8em;">
    <p>WildGuard Conservation Management System</p>
    <p>This report contains operational data for conservation management purposes.</p>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Escape HTML special characters
 */
function escapeHTML(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Format report type for display
 */
function formatReportType(reportType) {
  return reportType.replace(/_/g, " ");
}

module.exports = {
  exportToCSV,
  exportToHTML,
  escapeCSV,
  escapeHTML,
};
